sudo: false
os:
  - linux
language: scala
scala:
    - 2.12.1
jdk:
    - oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - liska.jakub@gmail.com
before_script:
    - rm -rf ${HOME}/.sbt/0.13/staging
script:
    - sbt ++$TRAVIS_SCALA_VERSION clean test